02_revenue_distribution_one_time_vs_repeat.sql
-- ============================================================
-- FILE: 02_revenue_distribution_one_time_vs_repeat.sql
-- OBJECTIVE:
-- Quantify the share of total revenue generated by one-time
-- vs repeat customers.
--
-- BUSINESS QUESTION:
-- Is revenue overly dependent on repeat customers, and how much
-- do one-time customers contribute to total revenue?
--
-- DATASET:
-- bigquery-public-data.thelook_ecommerce
-- ============================================================

WITH rpu AS (
  SELECT
    user_id,
    COUNT(DISTINCT order_id) AS orders_per_user,
    SUM(sale_price) AS revenue_per_user
  FROM `bigquery-public-data.thelook_ecommerce.order_items`
  GROUP BY user_id
),
customer_base AS (
  SELECT
    user_id,
    revenue_per_user,
    CASE
      WHEN orders_per_user = 1 THEN 'ONE_TIME'
      ELSE 'REPEAT'
    END AS customer_type
  FROM rpu
),
revenue_by_type AS (
  SELECT
    customer_type,
    SUM(revenue_per_user) AS total_revenue_per_customer_type
  FROM customer_base
  GROUP BY customer_type
)
SELECT
  customer_type,
  total_revenue_per_customer_type,
  SAFE_DIVIDE(
    total_revenue_per_customer_type,
    SUM(total_revenue_per_customer_type) OVER ()
  ) AS revenue_share
FROM revenue_by_type
ORDER BY revenue_share DESC;

-- RESULT (as of analysis):
-- REPEAT revenue_share ≈ 0.5978 (59.8%)
-- ONE_TIME revenue_share ≈ 0.4022 (40.2%)
--
-- INTERPRETATION:
-- Repeat customers generate ~59.8% of total revenue, while one-time customers
-- contribute ~40.2%.
--
-- This distribution is broadly consistent with typical non-luxury fashion
-- e-commerce patterns, where a minority of repeat customers often generates
-- between 55% and 70% of revenue.
--
-- Therefore, revenue concentration does not appear extreme or structurally
-- abnormal. The business does rely meaningfully on repeat customers,
-- but the distribution aligns with common sector benchmarks.
--
-- NEXT STEP:
-- Since both structural retention levels and revenue concentration metrics
-- fall within typical industry ranges, the slowdown hypothesis should be
-- further investigated through time-based analysis (monthly revenue trend,
-- customer growth trend, and retention evolution).
